#Angular JS
EXAMPLE_TEXT = "Example"
AJSOPTIMIZED_TEXT = "AngularJS Optimized"
TYPESCRIPTAJS_TEXT = "TypeScript & AngularJS"
GCLOUDPLATFORMEXPRESS_TEXT = "Google Cloud Platform + Express"
DEMO = "Demo"
SOURCE = "Source"

AJSTABLE_LABEL = [EXAMPLE_TEXT,EXAMPLE_TEXT,AJSOPTIMIZED_TEXT,TYPESCRIPTAJS_TEXT,GCLOUDPLATFORMEXPRESS_TEXT]
LINK_LABEL = [DEMO, SOURCE]

#Official Resources
TUTORIAL_TEXT = "Tutorial"
APIREF_TEXT = "API Reference"
DEVGUIDE_TEXT = "Developer Guide"
APPANGULARJS_TEXT = "Applications built with AngularJS"
BLOG_TEXT = "Blog"
FAQ_TEXT = "FAQ"
VIDEOS_TEXT = "Videos"

ORESOURCES_LABEL = [TUTORIAL_TEXT, APIREF_TEXT, DEVGUIDE_TEXT, APPANGULARJS_TEXT, BLOG_TEXT, FAQ_TEXT, VIDEOS_TEXT]

#Articles and Guides
CODEAJSCOURSE_TEXT = "Code School AngularJS course"
AWESOMEAJSFEATURES_TEXT = "5 Awesome AngularJS Features"
YEOMANAJS_TEXT = "Using Yeoman with AngularJS"
INTROMVW_TEXT = "me&ngular - an introduction to MVW"

ARTICLEGUIDE_LABEL = [CODEAJSCOURSE_TEXT, AWESOMEAJSFEATURES_TEXT, YEOMANAJS_TEXT, INTROMVW_TEXT]


#Community
TUTORIALYOUTUBE_TEXT = "Walkthroughs and Tutorials on YouTube"
GGMAILINGLIST_TEXT = "Google Groups mailing list"
AJSSTACKOVERFLOW_TEXT = "angularjs on Stack Overflow"
AJSTWITTER_TEXT = "AngularJS on Twitter"
AJSGOOGLEPLUS_TEXT = "AngularjS on Google+"

COMMUNITY_LABEL = [TUTORIALYOUTUBE_TEXT, GGMAILINGLIST_TEXT, AJSSTACKOVERFLOW_TEXT, AJSTWITTER_TEXT, AJSGOOGLEPLUS_TEXT]